/* question - Let’s create a project where we are trying to ask the user to guess a randomly generated number.
The number is in the range of 1 to 100.

If the user guesses a number that is greater, we print “The number is too large”.
If the user guesses a number that is smaller, we print “The number is too small”.
If the user is able to correctly guess the number, then we print “Correct Number!”.

At the end we will print the number that was generated by our Math library.*/

package Mypackage;

import java.util.Scanner;

public class MiniProject {

	public static void main(String[] args)
	{
	 	int mynumber = (int)(Math.random()*100);
	 	Scanner sc = new Scanner(System.in);
	 	int usernumber = 0;
	 	
	 	do
	 	{
	 		System.out.println("Guess the number 1-100");
	 		usernumber = sc.nextInt();
	 		
	 		if(usernumber == mynumber)
	 		{
	 			System.out.println("Correct Number!!!! ");
	 			break;
	 		}
	 		else if(usernumber > mynumber)
	 		{
	 			System.out.println("The number is too large");
	 		}
	 		else 
	 		{
	 			System.out.println("The number is too small");
	 		}
	 		
	 	}
	 	while(usernumber>=0);
	 	
	 	System.out.print("My number was");
	 	System.out.println(mynumber);
	}
}
